### PR TITLE
Only close our own opened files at go()

### PR DESCRIPTION
**Pull request by rapto**
We should only close files we opened. The practical problem solved is using a Django response or IO as output file. I have added check for closing the xml file, as I suppose the problem may arise when using a stream as xml input file.

### CODE REVIEW

**Comment by regebro** [comment]
You are quite correct, but I implemented this with context managers.

Thanks!

**Comment by orainova-ingentics** [comment]
It seems like this issue is still present? @regebro could you please elaborate on your workaround to avoid closing files? Currently, we're unable to use the library unless I fork it to fix closing the external BytesIO. Shall I open a new issue, since @rapto's PR has not been merged?

**Comment by rapto** [comment]
This (as current in master):
```py
    if hasattr(xmlInputName, 'read'):
        # it is already a file-like object
        xmlFile = xmlInputName
        xmlInputName = 'input.pdf'
    else:
        with open(xmlInputName, 'rb') as xmlFile:
            return go(xmlFile, outputFileName, outDir, dtdDir)
```
works fine in my case

**Comment by regebro** [comment]
@orainova-ingentics  A version with the changes has not been released, and it should be, that's correct. 

My fix looks at the input, and if it's an open file, it does not open or close it. If it is a path it will open it with a context manager. That ensures that it is closed.

**Pull request closed without merging**
