### PR TITLE
docs: README v1

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
Comments appreciated!

**Comment by CelestialGuru** [comment]
Would love to see this merged. The current README is a joke and this--even if it's not finished--at least gets me started.

**Review by regebro — APPROVED** [review]
Seems like a good idea

**Comment by Abdur-rahmaanJ** [comment]
@CelestialGuru and @regebro Thanks all, this is an awesome projects, just some docs missing!

**Pull request merged**
