### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by kedder**
Fix travis tests.

* Remove python-2.6 support (not supported by reportlab anymore)
* Install japanese font and fix japanese rendering
* Fix test isolation

### CODE REVIEW

**Comment by kedder** [comment]
After some struggle, travis is green! :cool:

**Comment by kylemacfarlane** [comment]
@kedder Sorry to be a pest, but is it possible to you to merge #27 as people keep asking when it will merged?

I ask here because I fixed these Travis issues in #27 back in January. There was a previous occasion where @strichter repeated a bunch of fixes for Reportlab 3.1.44 that I had also already done in #27.

When implementing Python 3 support I fixed lots of other little things along the way so there's more in the PR than just Py3 support and I don't want more people repeating work I've already done.

**Comment by kedder** [comment]
@kylemacfarlane, I'm not maintaining this project, but let me review #27 as I get home, and test it on our big python-2.7 project test suite, I think we can merge it. 

Can you make that branch mergeable?

**Comment by kylemacfarlane** [comment]
@kedder @stricher said he'd get someone to review the PR before merging. I did make the branch mergeable though.

**Pull request merged**
